### ISSUE TITLE
Livestream with multiple url

### ISSUE THREAD

**Issue by duyhct** [Softvelum/larix-sdk-examples#5]
Hi Softvelum, this library can support livestream with multiple URL in the same time?

**Comment by WMSPanel** [comment]
Yes, check all features description here: [https://softvelum.com/larix/](https://softvelum.com/larix/)
Feel free to subscribe to full SDK to get the streaming library and other examples: [https://softvelum.com/mobile/buy/](https://softvelum.com/mobile/buy/)
