### ISSUE TITLE
Will Larix send RTP with timestamps?

### ISSUE THREAD

**Issue by briveira** [Softvelum/larix-sdk-examples#7]
We are trying to send RTSP push video and audio but Larix is not sending absolute Timestamp clocks.  
Is there any plan to support sending RTP with real timestamps? (i.e. with current time from device)

Thanks

**Comment by WMSPanel** [comment]
Larix sends RTP sends NTP/RTP packet with NTP containing absolute time, before every key frame but not more frequent that every 5 seconds.
If you have any issues please send us [question to our helpdesk](https://wmspanel.com/help) so our engineers could help.
