### ISSUE TITLE
How to get camera broadcast with Stream instead of using the interface?

### ISSUE THREAD

**Issue by claudiooliveira** [Softvelum/larix-sdk-examples#9]
I need to stream the camera to the Flutter App, so I want another way to stream by working directly with the camera and sending that stream to flutter with the Method Channel. It is possible?

**Comment by WMSPanel** [comment]
At the moment we have Flutter only in our roadmap so unfortunately we cannot give any specific advises about your questions for now.

**Comment by claudiooliveira** [comment]
Hey @WMSPanel thanks for the answer. After asking this question, my team and I worked hard to solve the problem and if it is of interest to you, we have developed the flutter plugin for larix, we are now adapting it for IOS. If you want to save money with your team, we can negotiate the work we develop for you.

**Comment by WMSPanel** [comment]
@claudiooliveira can you please send your recent comment to https://wmspanel.com/help ? It's not shown here for some reason, probably because it's closed. Thanks!

**Comment by claudiooliveira** [comment]
Hey @WMSPanel  thanks for the answer. After asking this question, my team and I worked hard to solve the problem and if it is of interest to you, we have developed the flutter plugin for larix, we are now adapting it for IOS. If you want to save money with your team, we can negotiate the work we develop for you.

**Comment by WMSPanel** [comment]
That's a good news! Can you please drop a message to https://wmspanel.com/help with some example of such apploication so we could continue and evaluate this with our team?
